import { ArrowLeft, Check, Clipboard, Download, FileCode2, FileText, Gauge, Printer, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import { CoverLetterPreview, ResumePreview, coverLetterText } from './DocumentPreview'

export default function ResultsPanel({result,onNew}){
  const [tab,setTab]=useState('resume'),[copied,setCopied]=useState(false)
  const copy=async()=>{try{await navigator.clipboard.writeText(coverLetterText(result));setCopied(true);setTimeout(()=>setCopied(false),1700)}catch{/* browser fallback unavailable */}}
  const print=(type)=>{setTab(type);setTimeout(()=>window.print(),80)}
  return <div className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7 lg:px-9"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><button onClick={onNew} className="mb-3 inline-flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-slate-700"><ArrowLeft size={14}/> New tailoring</button><div className="flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-bold tracking-tight">{result.role_title}</h1><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-600">Ready</span></div><p className="mt-1 text-sm text-slate-400">{result.company_name} · {result.template_name}</p></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Gauge size={21} className="text-indigo-600"/><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">ATS match</p><p className="font-display text-xl font-black text-slate-900">{result.match_score}<span className="text-xs text-slate-400">/100</span></p></div></div></div>
    <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-2 sm:flex-row sm:items-center"><div className="flex flex-1 gap-1 overflow-x-auto">{[['resume',FileText,'Tailored resume'],['cover',Sparkles,'Cover letter'],['analysis',Gauge,'Match insights']].map(([key,Icon,label])=><button key={key} onClick={()=>setTab(key)} className={`flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-bold ${tab===key?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-50'}`}><Icon size={15}/>{label}</button>)}</div>{tab!=='analysis'&&<div className="flex gap-1 border-t border-slate-100 pt-2 sm:border-l sm:border-t-0 sm:pl-2 sm:pt-0">{tab==='cover'&&<button onClick={copy} className="toolbar-btn">{copied?<Check size={15} className="text-emerald-500"/>:<Clipboard size={15}/>} {copied?'Copied':'Copy text'}</button>}<a href={tab==='resume'?api.resumeTex(result.id):api.coverLetterTex(result.id)} className="toolbar-btn"><FileCode2 size={15}/> Overleaf .tex</a><button onClick={()=>print(tab)} className="toolbar-btn"><Printer size={15}/> Save PDF</button></div>}</div>
    {tab==='resume'&&<PreviewShell label="Your original layout · content tailored to this JD"><ResumePreview result={result} printCurrent/></PreviewShell>}
    {tab==='cover'&&<PreviewShell label="Your cover-letter format · personalized proof points"><CoverLetterPreview result={result} printCurrent/></PreviewShell>}
    {tab==='analysis'&&<Analysis result={result}/>}
  </div>
}

function PreviewShell({label,children}){return <div className="rounded-2xl border border-slate-200 bg-[#e9ebef] p-3 sm:p-8"><div className="no-print mb-4 flex items-center justify-center gap-2 text-[11px] font-bold uppercase tracking-[.14em] text-slate-400"><FileText size={13}/>{label}</div><div className="mx-auto overflow-x-auto pb-4"><div className="mx-auto w-[816px] origin-top">{children}</div></div></div>}
function Analysis({result}){return <div className="grid gap-5 lg:grid-cols-3"><Insight title="Matched keywords" icon={Check} tone="green" items={result.matched_keywords}/><Insight title="Genuine gaps" icon={Gauge} tone="amber" items={result.missing_keywords}/><Insight title="What changed" icon={Sparkles} tone="indigo" items={result.tailoring_notes}/></div>}
function Insight({title,icon:Icon,tone,items=[]}){const styles={green:'bg-emerald-50 text-emerald-600',amber:'bg-amber-50 text-amber-600',indigo:'bg-indigo-50 text-indigo-600'};return <section className="surface p-6"><span className={`grid h-10 w-10 place-items-center rounded-xl ${styles[tone]}`}><Icon size={18}/></span><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><div className="mt-4 flex flex-wrap gap-2">{items.length?items.map((item,i)=><span key={i} className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-xs leading-5 text-slate-600">{item}</span>):<p className="text-sm text-slate-400">None identified.</p>}</div></section>}
