import { ArrowRight, BriefcaseBusiness, Check, CloudCog, Eye, FileCheck2, FileText, LoaderCircle, Scale, ShieldCheck, Sparkles } from 'lucide-react'
import { api } from '../api'

export default function TailorForm({ form, setForm, templates, coverTemplate, onSubmit, loading }) {
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const words = form.job_description.trim() ? form.job_description.trim().split(/\s+/).length : 0
  return <div className="mx-auto max-w-[1280px] px-4 py-8 sm:px-7 lg:px-10 lg:py-11">
    <div className="mb-9 max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.12em] text-indigo-600"><Sparkles size={13}/> Built from your real resume</div><h1 className="font-display text-4xl font-bold tracking-[-.035em] text-slate-950 sm:text-5xl">One job description.<br/><span className="text-slate-400">Two documents, tailored.</span></h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-500">Choose one of your resume templates, paste the role, and get an ATS-focused resume plus a personalized cover letter in your established format.</p></div>
    <form onSubmit={onSubmit} className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_390px]">
      <div className="space-y-7">
        <section className="surface p-5 sm:p-7"><Step number="01" title="Tell me about the role" description="These details personalize both documents."/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Company"><input required className="input" value={form.company_name} onChange={e=>update('company_name',e.target.value)} placeholder="e.g. Amazon"/></Field><Field label="Role title"><input required className="input" value={form.role_title} onChange={e=>update('role_title',e.target.value)} placeholder="e.g. Cloud Support Engineer"/></Field><Field label="Location" optional><input className="input" value={form.location} onChange={e=>update('location',e.target.value)} placeholder="e.g. Bengaluru, India"/></Field><Field label="Job ID" optional><input className="input" value={form.job_id} onChange={e=>update('job_id',e.target.value)} placeholder="e.g. 2841021"/></Field><Field label="Hiring manager / team" optional wide><input className="input" value={form.hiring_manager} onChange={e=>update('hiring_manager',e.target.value)} placeholder="Recruiting Team"/></Field></div></section>
        <section className="surface p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><Step number="02" title="Paste the job description" description="Include responsibilities, requirements, and preferred skills."/><span className={`mt-1 whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-bold ${words >= 80 ? 'bg-emerald-50 text-emerald-600':'bg-slate-100 text-slate-400'}`}>{words} words</span></div><textarea required minLength={80} className="input mt-6 min-h-[330px] resize-y font-mono text-[13px] leading-6" value={form.job_description} onChange={e=>update('job_description',e.target.value)} placeholder={'Paste the complete job description here…\n\nTip: the fuller the JD, the stronger the keyword matching and cover-letter personalization.'}/><div className="mt-4"><Field label="Extra direction" optional><input className="input" value={form.extra_instructions} onChange={e=>update('extra_instructions',e.target.value)} placeholder="e.g. Emphasize Kubernetes and client communication"/></Field></div></section>
      </div>
      <aside className="space-y-6 xl:sticky xl:top-8 xl:self-start"><section className="surface p-5 sm:p-6"><Step number="03" title="Choose your base" description="Its structure and layout family stay locked."/><div className="mt-5 space-y-3">{templates.map(template => { const selected=form.template_id===template.id; const Icon=template.track.toLowerCase().includes('cloud')?CloudCog:BriefcaseBusiness; return <button type="button" key={template.id} onClick={()=>update('template_id',template.id)} className={`w-full rounded-2xl border p-4 text-left transition ${selected?'border-slate-950 bg-slate-950 text-white shadow-lg shadow-slate-950/10':'border-slate-200 bg-white hover:border-slate-300'}`}><div className="flex items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${selected?'bg-white/10 text-white':'bg-slate-100 text-slate-600'}`}><Icon size={19}/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-bold">{template.name}{selected&&<Check size={14} className="text-emerald-400"/>}</span><span className={`mt-1 block truncate text-xs leading-5 ${selected?'text-slate-400':'text-slate-500'}`}>{template.track} · {template.filename}</span><a href={api.originalTemplate(template.id)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} className={`mt-3 inline-flex items-center gap-1 text-[11px] font-bold ${selected?'text-sky-300':'text-indigo-600'}`}><Eye size={13}/> View original</a></span></div></button>})}</div>{coverTemplate&&<a href={api.originalTemplate(coverTemplate.id)} target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2.5 text-xs font-bold text-amber-700"><FileText size={15}/> Cover-letter format locked <Eye className="ml-auto" size={14}/></a>}</section>
        <section className="overflow-hidden rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-600 p-6 text-white shadow-xl shadow-indigo-200"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.15em] text-indigo-100"><FileCheck2 size={16}/> Ready to tailor</div><p className="mt-4 text-sm leading-6 text-indigo-100">Gemini will reframe only evidence already present in your selected resume.</p><button disabled={loading||words<10||!form.template_id} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3.5 text-sm font-black text-indigo-700 shadow-sm hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-60">{loading?<LoaderCircle size={18} className="animate-spin"/>:<Sparkles size={18}/>} {loading?'Tailoring both documents…':'Generate tailored set'} {!loading&&<ArrowRight size={17}/>}</button><div className="mt-4 flex items-center justify-center gap-4 text-[10px] font-semibold text-indigo-200"><span className="flex items-center gap-1"><ShieldCheck size={12}/> Truth checked</span><span className="flex items-center gap-1"><Scale size={12}/> ATS balanced</span></div></section>
      </aside>
    </form>
  </div>
}

function Step({number,title,description}){return <div className="flex gap-3"><span className="mt-0.5 font-mono text-xs font-bold text-indigo-500">{number}</span><div><h2 className="font-display text-lg font-bold tracking-tight text-slate-900">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div></div>}
function Field({label,optional,wide,children}){return <label className={wide?'sm:col-span-2':''}><span className="label">{label}{optional&&<span className="ml-1.5 font-normal normal-case tracking-normal text-slate-300">optional</span>}</span>{children}</label>}
